Repository vmware/packer-examples-for-vsphere, pull requests merged in 2021-10, with the labels that each got.

#79 Update Packer to `>= 1.7.6`
  README.md
  builds/linux/almalinux-8/linux-almalinux.pkr.hcl
  builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
  builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
  builds/linux/photon-4/linux-photon.pkr.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/windows/windows-server-2016/windows-server.pkr.hcl
  builds/windows/windows-server-2019/windows-server.pkr.hcl
  builds/windows/windows-server-2022/windows-server.pkr.hcl
Labels: docs, enhancement, priority:low, status:fix-committed, sev:low, size:xs

#81 Correct typo in docs for environmental variables
  README.md
Labels: docs, status:needs-review, priority:low, sev:minor, size:xs

#83 Add HTTP IP address option
  README.md
  builds/common.pkrvars.hcl.example
  builds/linux/almalinux-8/linux-almalinux.pkr.hcl
  builds/linux/almalinux-8/variables.pkr.hcl
  builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
  builds/linux/centos-linux-8/variables.pkr.hcl
  builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
  builds/linux/centos-stream-8/variables.pkr.hcl
  builds/linux/photon-4/linux-photon.pkr.hcl
  builds/linux/photon-4/variables.pkr.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  builds/linux/redhat-linux-8/variables.pkr.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
  builds/linux/rocky-linux-8/variables.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl
Labels: docs, enhancement, status:needs-review, priority:medium, status:fix-committed, sev:minor, size:s

#84 Add header to `build.sh` and `config.sh`
  build.sh
  config.sh
Labels: priority:low, status:fix-committed, sev:low, size:xs

#85 Add public keys to `.gitignore`
  .gitignore
Labels: enhancement, priority:medium, status:fix-committed, sev:minor, size:xs

#89 Fix typo in `autounattend.pkrtpl.hcl`
  builds/windows/windows-server-2016/data/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2019/data/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2022/data/autounattend.pkrtpl.hcl
Labels: bug, priority:medium, priority:high, status:fix-committed, sev:minor, size:xs

#88 Add Windows 10 Professional
  README.md
  build.sh
  builds/windows/windows-10/data/autounattend.pkrtpl.hcl
  builds/windows/windows-10/variables.pkr.hcl
  builds/windows/windows-10/windows.auto.pkrvars.hcl
  builds/windows/windows-10/windows.pkr.hcl
Labels: enhancement, status:under-review, priority:medium, status:fix-committed, sev:low, size:m

#92 Remove `<ComputerName/>` from `autounattend.pkrtpl.hcl`
  builds/windows/windows-10/data/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2016/data/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2019/data/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2022/data/autounattend.pkrtpl.hcl
Labels: bug, priority:medium, status:fix-committed, sev:minor, size:s

#93 Refactor ISOs and adjacent bug-fixes
  README.md
  build.sh
  builds/common.pkrvars.hcl.example
  builds/linux/almalinux-8/linux-almalinux.auto.pkrvars.hcl
  builds/linux/almalinux-8/linux-almalinux.pkr.hcl
  builds/linux/almalinux-8/variables.pkr.hcl
  builds/linux/centos-linux-8/linux-centos-linux.auto.pkrvars.hcl
  builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
  builds/linux/centos-linux-8/variables.pkr.hcl
  builds/linux/centos-stream-8/linux-centos-stream.auto.pkrvars.hcl
  builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
  builds/linux/centos-stream-8/variables.pkr.hcl
  builds/linux/photon-4/data/ks.pkrtpl.hcl
  builds/linux/photon-4/linux-photon.auto.pkrvars.hcl
  builds/linux/photon-4/linux-photon.pkr.hcl
  builds/linux/photon-4/variables.pkr.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.auto.pkrvars.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  builds/linux/redhat-linux-8/variables.pkr.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.auto.pkrvars.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
  builds/linux/rocky-linux-8/variables.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/data/ks.pkrtpl.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.auto.pkrvars.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/data/user-data.pkrtpl.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.auto.pkrvars.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl
  builds/windows/windows-10/variables.pkr.hcl
  builds/windows/windows-10/windows.auto.pkrvars.hcl
  builds/windows/windows-10/windows.pkr.hcl
  builds/windows/windows-server-2016/variables.pkr.hcl
  builds/windows/windows-server-2016/windows-server.auto.pkrvars.hcl
  builds/windows/windows-server-2016/windows-server.pkr.hcl
  builds/windows/windows-server-2019/variables.pkr.hcl
  builds/windows/windows-server-2019/windows-server.auto.pkrvars.hcl
  builds/windows/windows-server-2019/windows-server.pkr.hcl
  builds/windows/windows-server-2022/variables.pkr.hcl
  builds/windows/windows-server-2022/windows-server.auto.pkrvars.hcl
  builds/windows/windows-server-2022/windows-server.pkr.hcl
  scripts/linux/redhat-derivative.sh
Labels: bug, docs, enhancement, refactor, priority:medium, status:fix-committed, sev:minor, size:l

#96 Update Ubuntu 20.04 LTS to `efi-secure`
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.auto.pkrvars.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl
Labels: enhancement, refactor, priority:medium, status:fix-committed, sev:minor, size:s

#97 Update method for adding epel repository for rhel8
  scripts/linux/redhat-linux.sh
Labels: bug, priority:medium, status:fix-committed, status:confirmed, sev:major, size:xs

#98 Add project version and 'main` to issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: enhancement, priority:medium, status:fix-committed, sev:major, size:xs

#99 Revert to Photon OS 4.0 GA from 4.0 Revision 1
  README.md
  builds/linux/photon-4/linux-photon.auto.pkrvars.hcl
Labels: bug, priority:medium, status:fix-committed, sev:major, size:s

#100 Check HCL format and trim trailing whitespace
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
  NOTICE
  README.md
  builds/ansible.pkrvars.hcl.example
  builds/build.pkrvars.hcl.example
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/proxy.pkrvars.hcl.example
  builds/rhsm.pkrvars.hcl.example
  builds/vsphere.pkrvars.hcl.example
  builds/windows/windows-10/windows.pkr.hcl
Labels: priority:low, status:fix-committed, sev:low, size:xs

#102 Update issue templates
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
Labels: enhancement, priority:low, status:fix-committed, sev:low, size:xs

#105 Add the ansible package and dependencies to rhel
  builds/linux/redhat-linux-8/data/ks.pkrtpl.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  scripts/linux/redhat-linux.sh
Labels: enhancement, priority:medium, status:fix-committed, sev:minor, size:s

#106 Remove `sudo` from the `ks.pkrtpl.hcl` for rhel-derivatives
  builds/linux/almalinux-8/data/ks.pkrtpl.hcl
  builds/linux/centos-linux-8/data/ks.pkrtpl.hcl
  builds/linux/centos-stream-8/data/ks.pkrtpl.hcl
  builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl
Labels: refactor, priority:low, status:fix-committed, sev:low, size:xs

#110 Update rhel/rhel-derivative kickstart configurations and scripts
  builds/linux/almalinux-8/data/ks.pkrtpl.hcl
  builds/linux/centos-linux-7/data/ks.pkrtpl.hcl
  builds/linux/centos-linux-8/data/ks.pkrtpl.hcl
  builds/linux/centos-stream-8/data/ks.pkrtpl.hcl
  builds/linux/redhat-linux-7/data/ks.pkrtpl.hcl
  builds/linux/redhat-linux-8/data/ks.pkrtpl.hcl
  builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl
  scripts/linux/rhel7-derivative.sh
  scripts/linux/rhel7.sh
  scripts/linux/rhel8-derivative.sh
  scripts/linux/rhel8.sh
Labels: enhancement, priority:medium, status:fix-committed, sev:low, size:m

#112 Fix typo in rhel/rhel-derivative kickstart
  builds/linux/almalinux-8/data/ks.pkrtpl.hcl
  builds/linux/centos-linux-7/data/ks.pkrtpl.hcl
  builds/linux/centos-linux-8/data/ks.pkrtpl.hcl
  builds/linux/centos-stream-8/data/ks.pkrtpl.hcl
  builds/linux/redhat-linux-7/data/ks.pkrtpl.hcl
  builds/linux/redhat-linux-8/data/ks.pkrtpl.hcl
  builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl
Labels: bug, priority:low, status:fix-committed, sev:low, size:xs

#113 Update `photon.sh` to remove duplicate package installs
  scripts/linux/photon.sh
Labels: bug, priority:low, status:fix-committed, sev:low, size:xs

#114 Add `partitions` to `ks.pkrtpl.hcl` for photon
  builds/linux/photon-4/data/ks.pkrtpl.hcl
Labels: enhancement, priority:medium, status:fix-committed, sev:low, size:xs

#109 Add Ansible provisioner and playbook for Ubuntu 20.04 + 18.04
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  scripts/ansible/playbook.yml
  scripts/linux/ubuntu-server-18.sh
  scripts/linux/ubuntu-server-2x.sh
Labels: enhancement, status:in-progress, priority:medium, sev:low, size:m
