Repository vmware/packer-examples-for-vsphere, pull requests merged in 2021-09, with the labels that each got.

#28 Update README.md and build.sh.
  README.md
  build.sh
Labels: documentation, refactor

#44 Make content_library_destination optional
  builds/linux/almalinux-8/linux-almalinux.pkr.hcl
  builds/linux/almalinux-8/variables.pkr.hcl
  builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
  builds/linux/centos-linux-8/variables.pkr.hcl
  builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
  builds/linux/centos-stream-8/variables.pkr.hcl
  builds/linux/photon-4/linux-photon.pkr.hcl
  builds/linux/photon-4/variables.pkr.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  builds/linux/redhat-linux-8/variables.pkr.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
  builds/linux/rocky-linux-8/variables.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl
  builds/windows/windows-server-2016/variables.pkr.hcl
  builds/windows/windows-server-2016/windows-server.pkr.hcl
  builds/windows/windows-server-2019/variables.pkr.hcl
  builds/windows/windows-server-2019/windows-server.pkr.hcl
  builds/windows/windows-server-2022/variables.pkr.hcl
  builds/windows/windows-server-2022/windows-server.pkr.hcl
Labels: bug, refactor, planned

#46 Update boot_command for rhel/variants
  builds/linux/almalinux-8/linux-almalinux.pkr.hcl
  builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
  builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
Labels: refactor

#47 Update ks.pkrtpl.hcl for rhel/variants
  builds/linux/almalinux-8/http/ks.pkrtpl.hcl
  builds/linux/centos-linux-8/http/ks.pkrtpl.hcl
  builds/linux/centos-stream-8/http/ks.pkrtpl.hcl
  builds/linux/redhat-linux-8/http/ks.pkrtpl.hcl
  builds/linux/rocky-linux-8/http/ks.pkrtpl.hcl
Labels: refactor

#48 Update ks.pkrtpl.hcl for rhel/variants
  builds/linux/almalinux-8/http/ks.pkrtpl.hcl
  builds/linux/centos-linux-8/http/ks.pkrtpl.hcl
  builds/linux/centos-stream-8/http/ks.pkrtpl.hcl
  builds/linux/redhat-linux-8/http/ks.pkrtpl.hcl
  builds/linux/rocky-linux-8/http/ks.pkrtpl.hcl
Labels: bug

#53 Fix Ubuntu 20.04 user-data
  builds/linux/ubuntu-server-20-04-lts/http/user-data.pkrtpl.hcl
Labels: bug

#40 Support ssh_proxy_* variables for Linux images
  README.md
  build.sh
  builds/linux/almalinux-8/linux-almalinux.pkr.hcl
  builds/linux/almalinux-8/variables.pkr.hcl
  builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
  builds/linux/centos-linux-8/variables.pkr.hcl
  builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
  builds/linux/centos-stream-8/variables.pkr.hcl
  builds/linux/photon-4/linux-photon.pkr.hcl
  builds/linux/photon-4/variables.pkr.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  builds/linux/redhat-linux-8/variables.pkr.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
  builds/linux/rocky-linux-8/variables.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl
  builds/proxy.pkrvars.hcl
Labels: under-review

#61 Revert to ens33 for Ubuntu 20.04 LTS
  builds/linux/ubuntu-server-20-04-lts/http/user-data.pkrtpl.hcl
Labels: bug, priority:high, status:resolved, sev:critical, size:s

#64 Rename `cd` to `data`
  README.md
  builds/windows/windows-server-2016/cd/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2016/windows-server.pkr.hcl
  builds/windows/windows-server-2019/data/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2019/windows-server.pkr.hcl
  builds/windows/windows-server-2022/data/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2022/windows-server.pkr.hcl
Labels: refactor, priority:low, status:fix-committed, sev:low, size:xs

#65 Rename certificates to`.example` extension
  .gitignore
  README.md
  certificates/root-ca.crt.example
  certificates/root-ca.p7b.example
Labels: docs, priority:low, status:fix-committed, sev:low, size:xs

#66 Refactor manifest output location.
  .gitignore
  builds/linux/almalinux-8/linux-almalinux.auto.pkrvars.hcl
  builds/linux/almalinux-8/linux-almalinux.pkr.hcl
  builds/linux/centos-linux-8/linux-centos-linux.auto.pkrvars.hcl
  builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
  builds/linux/centos-linux-8/output/.gitkeep
  builds/linux/centos-stream-8/linux-centos-stream.auto.pkrvars.hcl
  builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
  builds/linux/centos-stream-8/output/.gitkeep
  builds/linux/photon-4/linux-photon.auto.pkrvars.hcl
  builds/linux/photon-4/linux-photon.pkr.hcl
  builds/linux/photon-4/output/.gitkeep
  builds/linux/redhat-linux-8/linux-redhat-linux.auto.pkrvars.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  builds/linux/redhat-linux-8/output/.gitkeep
  builds/linux/rocky-linux-8/linux-rocky-linux.auto.pkrvars.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
  builds/linux/rocky-linux-8/output/.gitkeep
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.auto.pkrvars.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/output/.gitkeep
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.auto.pkrvars.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/output/.gitkeep
  builds/windows/windows-server-2016/data/autounattend.pkrtpl.hcl
  builds/windows/windows-server-2016/output/.gitkeep
  builds/windows/windows-server-2016/windows-server.pkr.hcl
  builds/windows/windows-server-2019/output/.gitkeep
  builds/windows/windows-server-2019/windows-server.pkr.hcl
  builds/windows/windows-server-2022/output/.gitkeep
  builds/windows/windows-server-2022/windows-server.pkr.hcl
  manifests/.gitkeep
Labels: refactor, priority:medium, status:fix-committed, sev:low, size:s

#67 Update PhotonOS to `efi-secure`
  builds/linux/photon-4/data/ks.pkrtpl.hcl
  builds/linux/photon-4/linux-photon.auto.pkrvars.hcl
  builds/linux/photon-4/linux-photon.pkr.hcl
Labels: enhancement, priority:low, status:fix-committed, sev:low, size:s

#69 Update `build.sh` to remove `rm -f output-vmware-iso/*.ova`
  build.sh
Labels: enhancement, priority:low, status:fix-committed, sev:low, size:xs

#70 Fix typo in `.gitignore`
  .gitignore
Labels: bug, priority:medium, status:fix-committed, sev:minor, size:xs

#75 Add ansible to rhel-variants
  builds/linux/almalinux-8/data/ks.pkrtpl.hcl
  builds/linux/centos-linux-8/data/ks.pkrtpl.hcl
  builds/linux/centos-stream-8/data/ks.pkrtpl.hcl
  builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl
Labels: enhancement, priority:medium, status:fix-committed, sev:minor, size:s

#71 Allow Packer to be launched from any directory
  README.md
  build.sh
  builds/linux/almalinux-8/linux-almalinux.auto.pkrvars.hcl
  builds/linux/almalinux-8/linux-almalinux.pkr.hcl
  builds/linux/centos-linux-8/linux-centos-linux.auto.pkrvars.hcl
  builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
  builds/linux/centos-stream-8/linux-centos-stream.auto.pkrvars.hcl
  builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
  builds/linux/photon-4/linux-photon.auto.pkrvars.hcl
  builds/linux/photon-4/linux-photon.pkr.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.auto.pkrvars.hcl
  builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.auto.pkrvars.hcl
  builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.auto.pkrvars.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.auto.pkrvars.hcl
  builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
  builds/windows/windows-server-2016/windows-server.auto.pkrvars.hcl
  builds/windows/windows-server-2016/windows-server.pkr.hcl
  builds/windows/windows-server-2019/windows-server.auto.pkrvars.hcl
  builds/windows/windows-server-2019/windows-server.pkr.hcl
  builds/windows/windows-server-2022/windows-server.auto.pkrvars.hcl
  builds/windows/windows-server-2022/windows-server.pkr.hcl
Labels: enhancement, refactor, status:needs-review, priority:medium, sev:low, size:s

#77 Refactor scripts to use `dnf` for rhel8 + rhel8-variants
  scripts/linux/redhat-linux.sh
  scripts/linux/redhat-variant.sh
Labels: enhancement, priority:medium, status:fix-committed, sev:minor, size:s

#78 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs
