Repository vmware/packer-examples-for-vsphere, pull requests merged in 2021-11, with the labels that each got.

#125 Custom partitioning for Ubuntu
  .gitignore
  builds/linux/ubuntu-server-18-04-lts/data/ks.pkrtpl.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.auto.pkrvars.hcl
  builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
  builds/linux/ubuntu-server-18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu-server-20-04-lts/data/user-data.pkrtpl.hcl
Labels: type/enhancement, status/needs-review, priority/medium, sev/low, size/m

#138 Enable cloud-init `VMware` data source on Ubuntu 20.04
  builds/linux/ubuntu-server-20-04-lts/data/user-data.pkrtpl.hcl
  scripts/linux/ubuntu-server-2x.sh
Labels: type/enhancement, status/needs-review, priority/medium, sev/low, size/s

#139 Add example playbook for custom vSphere role
  ansible/vsphere-role.yml
Labels: type/enhancement, priority/low, sev/low, size/xs

#142 Fix symbol error in `ubuntu-server-2x.sh`
  scripts/linux/ubuntu-server-2x.sh
Labels: priority/high, sev/low, size/xs

#143 Adds GiitHub Actions
  .github/comment_template.md
  .github/workflows/issue-greeting.yml
  .github/workflows/lock.yml
  .github/workflows/pull-request-sizing.yml
  .github/workflows/pull-request-wip.yml
  .github/workflows/stale.yml
Labels: type/enhancement, status/needs-review, priority/medium, sev/low, size/s
