Repository vmware/packer-examples-for-vsphere, pull requests merged in 2022-09, with the labels that each got.

#272 fix: add support for disk-based deployment mode for Debian 11
  builds/linux/debian/11/data/ks.pkrtpl.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
Labels: type/enhancement, status/planned, status/needs-review, priority/medium, sev/low

#273 chore(deps): bump debian from v11.4.0 to v11.5.0
  builds/linux/debian/11/linux-debian.auto.pkrvars.hcl
Labels: priority/medium, sev/low, size/xs, type/chore

#275 chore(deps): bump ubuntu from v20.04.4 to v20.04.5
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.auto.pkrvars.hcl
Labels: priority/medium, sev/low, size/xs, type/chore

#276 fix: add support for disk-based deployment mode for SLES 15
  builds/linux/sles/15/linux-sles.pkr.hcl
Labels: type/enhancement, priority/medium, sev/low, size/xs

#277 chore: run `packer fmt`
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: priority/low, sev/low, type/chore

#278 fix: correct typos
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2022/variables.pkr.hcl
Labels: type/bug, priority/low, sev/low, size/xs

#279 refactor: remove unnecessary defaults
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/almalinux/9/variables.pkr.hcl
  builds/linux/centos/7/variables.pkr.hcl
  builds/linux/centos/8-stream/variables.pkr.hcl
  builds/linux/centos/9-stream/variables.pkr.hcl
  builds/linux/debian/11/variables.pkr.hcl
  builds/linux/photon/4/variables.pkr.hcl
  builds/linux/rhel/7/variables.pkr.hcl
  builds/linux/rhel/8/variables.pkr.hcl
  builds/linux/rhel/9/variables.pkr.hcl
  builds/linux/rocky/8/variables.pkr.hcl
  builds/linux/rocky/9/variables.pkr.hcl
  builds/linux/sles/15/variables.pkr.hcl
  builds/linux/ubuntu/18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2022/variables.pkr.hcl
Labels: type/refactor, priority/medium, sev/low, size/s

#280 docs: address `markdownlint` findings
  CHANGELOG.md
  README.md
Labels: type/docs

#281 fix: update windows server source names
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/bug

#282 chore(deps): bump windows server 2022 to september 2022
  builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Labels: priority/medium, sev/low, size/xs, type/chore

#283 chore(deps): bump windows 10 to 21h2 september 2022
  builds/windows/desktop/10/windows.auto.pkrvars.hcl
Labels: priority/medium, sev/low, size/xs, type/chore

#286 chore(deps): bump `terraform` from v1.2.8 to v1.3.0
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: priority/medium, sev/low, size/s, type/chore, dependencies

#287 chore(deps): bump sles from v15.3 to v15.4
  README.md
  builds/linux/sles/15/data/autoinst.pkrtpl.hcl
  builds/linux/sles/15/linux-sles.auto.pkrvars.hcl
Labels: priority/medium, sev/low, size/xs, type/chore, dependencies

#290 docs: update `README.md`
  README.md
Labels: type/docs, status/planned, priority/medium, sev/low

#291 fix: rename `comment_template.md`
  .github/comment-template.md
Labels: type/bug, github-actions

#284 chore(deps): bump windows 11 to 22h2 september 2022
  builds/windows/desktop/11/windows.auto.pkrvars.hcl
  scripts/windows/windows-init.ps1
Labels: priority/medium, sev/low, size/xs, type/chore, dependencies

#292 chore(deps): bump terraform from v1.3.0 to v1.3.1
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: priority/medium, sev/low, size/xs, type/chore, dependencies
