Repository vmware/packer-examples-for-vsphere, pull requests merged in 2022-11, with the labels that each got.

#326 docs: update `README.md`
  README.md
Labels: type/docs

#327 chore: update ansible yaml
  ansible/ansible.cfg
  ansible/main.yml
  ansible/roles/base/defaults/main.yml
  ansible/roles/base/tasks/photon.yml
  ansible/roles/base/tasks/sles.yml
  ansible/roles/base/vars/main.yml
  ansible/roles/clean/tasks/redhat.yml
  ansible/roles/clean/tasks/sles.yml
Labels: type/chore

#328 chore(deps): bump packer from v1.8.3 to v1.8.4
  .github/ISSUE_TEMPLATE/bug.yml
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/chore, dependencies

#329 chore(deps): bump packer-plugin-vsphere from v1.0.8 to v1.1.0
  .github/ISSUE_TEMPLATE/bug.yml
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/chore, dependencies

#330 chore(deps): bump terraform from v1.3.1 to v1.3.4
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, dependencies

#331 chore(gh): add `.gitleaks.toml`
  .gitleaks.toml
Labels: type/chore

#334 feat: localized local administrator
  scripts/windows/windows-prepare.ps1
Labels: type/enhancement, size/xs

#335 feat: localized remote desktop
  scripts/windows/windows-prepare.ps1
Labels: type/enhancement, size/xs

#339 fix: update custom role privileges
  README.md
  terraform/vsphere-role/terraform.tfvars.example
Labels: type/bug, type/docs, terraform

#342 refactor: update debian disk provisioning
  builds/linux/debian/11/linux-debian.auto.pkrvars.hcl
Labels: type/refactor

#360 docs: update `MAINTAINERS.md`
  MAINTAINERS.md
Labels: type/docs

#361 chore(deps): bump almalinux from v8.6 to v8.7
  builds/linux/almalinux/8/linux-almalinux.auto.pkrvars.hcl
Labels: type/chore, dependencies

#362 chore(deps): bump almalinux from v9.0 to v9.1
  builds/linux/almalinux/9/linux-almalinux.auto.pkrvars.hcl
Labels: type/chore, dependencies

#364 chore(deps): bump centos stream 9 to latest
  builds/linux/centos/9-stream/linux-centos-stream.auto.pkrvars.hcl
Labels: type/chore, dependencies

#365 chore(deps): bump rhel from v8.6 to v8.7
  builds/linux/rhel/8/linux-rhel.auto.pkrvars.hcl
Labels: type/chore, dependencies

#366 chore(deps): bump rhel from v9.0 to v9.1
  builds/linux/rhel/9/linux-rhel.auto.pkrvars.hcl
Labels: type/chore, dependencies

#367 chore: update rocky linux 9 `vm_guest_os_version`
  builds/linux/rocky/9/linux-rocky.auto.pkrvars.hcl
Labels: type/chore, dependencies

#368 chore(deps): bump rocky linux from v8.6 to v8.7
  builds/linux/rocky/8/linux-rocky.auto.pkrvars.hcl
Labels: type/chore, dependencies

#369 chore: update debian `vm_guest_os_version`
  builds/linux/debian/11/linux-debian.auto.pkrvars.hcl
Labels: type/chore, dependencies

#370 chore: update photon 4 `vm_guest_os_version`
  builds/linux/photon/4/linux-photon.auto.pkrvars.hcl
Labels: type/chore, dependencies

#371 chore: update sles `vm_guest_os_version`
  builds/linux/sles/15/linux-sles.auto.pkrvars.hcl
Labels: type/chore, dependencies

#373 chore(deps): bump windows server 2019 to latest
  builds/windows/server/2019/windows-server.auto.pkrvars.hcl
Labels: type/chore, dependencies

#374 chore(deps): bump windows 10 to 22h2 november 2022
  builds/windows/desktop/10/windows.auto.pkrvars.hcl
Labels: type/chore, dependencies

#375 chore(deps): bump windows 11 to 22h2 november 2022
  builds/windows/desktop/11/windows.auto.pkrvars.hcl
Labels: type/chore, dependencies

#376 chore(deps): bump windows server 2022 to latest
  builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Labels: type/chore, dependencies

#377 docs: update `README.md`
  README.md
Labels: type/chore, dependencies

#378 chore(deps): bump terraform from v1.3.4 to v1.3.5
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, dependencies

#381 chore(deps): bump rocky linux from v9.0 to v9.1
  builds/linux/rocky/9/linux-rocky.auto.pkrvars.hcl
Labels: type/chore, dependencies

#382 chore(deps): bump gomplate from v3.11.2 to v3.11.3
  README.md
Labels: type/chore, dependencies

#389 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: type/docs

#385 refactor: Use Git branch / tag for versioning
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/refactor, size/m

#390 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: type/docs

#391 chore(deps): bump terraform from v1.3.5 to v1.3.6
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, dependencies

#392 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: type/docs

#393 docs: update `README.md`
  README.md
Labels: type/docs
