Repository vmware/packer-examples-for-vsphere, pull requests merged in 2022-07, with the labels that each got.

#214 chore(deps): Bump `github.com/hashicorp/vsphere` from 1.0.5 to 1.0.6
  .github/ISSUE_TEMPLATE/bug.yml
  CHANGELOG.md
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8/linux-centos.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2016/windows-server.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: priority/low, sev/low, size/s, type/chore

#219 Remove deprecated builds for CentOS 8 and Windows Server 2016
  builds/linux/centos/8/data/ks.pkrtpl.hcl
  builds/linux/centos/8/linux-centos.auto.pkrvars.hcl
  builds/linux/centos/8/linux-centos.pkr.hcl
  builds/linux/centos/8/variables.pkr.hcl
  builds/windows/server/2016/data/autounattend.pkrtpl.hcl
  builds/windows/server/2016/variables.pkr.hcl
  builds/windows/server/2016/windows-server.auto.pkrvars.hcl
  builds/windows/server/2016/windows-server.pkr.hcl
  scripts/windows/windows-vmtools.ps1
Labels: type/chore

#221 chore(deps): Bump `terraform` from `>= v1.2.3` to `>= v1.2.5`
  CHANGELOG.md
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: priority/low, sev/low, type/chore

#220 feat: Add support for RHEL 9.0 + GA derivatives (2 of 2)
  CHANGELOG.md
  build.sh
  build.yaml
  builds/linux/rocky/9/data/ks.pkrtpl.hcl
  builds/linux/rocky/9/linux-rocky.auto.pkrvars.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/rocky/9/variables.pkr.hcl
Labels: type/enhancement, priority/high, status/fix-committed, sev/low, size/s

#223 enhance: Remove trusted root authority certificate pre-requisite
  CHANGELOG.md
  README.md
  ansible/roles/base/files/root-ca.cer.example
  ansible/roles/base/handlers/main.yml
  ansible/roles/base/tasks/photon.yml
  ansible/roles/base/tasks/redhat.yml
  ansible/roles/base/tasks/ubuntu.yml
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  certificates/root-ca.cer.example
  scripts/windows/windows-prepare.ps1
Labels: type/enhancement, priority/high, sev/low, size/s

#224 fix: Set user context for Ansible provisioner
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
Labels: type/bug, priority/low, size/s

#225 refactor: Additional use of local variables
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/refactor, priority/medium, sev/low

#226 feat: Add common option to export machine image artifacts
  CHANGELOG.md
  README.md
  artifacts/.gitkeep
  builds/common.pkrvars.hcl.example
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/variables.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/7/variables.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8-stream/variables.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/variables.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/4/variables.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/7/variables.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/8/variables.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rhel/9/variables.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/8/variables.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/rocky/9/variables.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/variables.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  set-envvars.sh
Labels: priority/high, sev/low, type/feature, size/l

#227 enhance: Add support for SLES 15 (SP3) machine image
  README.md
  ansible/roles/base/tasks/main.yml
  ansible/roles/base/tasks/sles.yml
  ansible/roles/clean/tasks/main.yml
  ansible/roles/clean/tasks/sles.yml
  ansible/roles/configure/tasks/main.yml
  ansible/roles/configure/tasks/sles.yml
  ansible/roles/users/tasks/main.yml
  build.sh
  build.yaml
  builds/linux/sles/15/data/autoinst.pkrtpl.hcl
  builds/linux/sles/15/linux-sles.auto.pkrvars.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/sles/15/variables.pkr.hcl
  builds/scc.pkrvars.hcl.example
  set-envvars.sh
Labels: type/enhancement, status/planned, priority/high, sev/low, size/xl
