Repository vmware/packer-examples-for-vsphere, pull requests merged in 2022-01, with the labels that each got.

#150 Fix typo in README.md
  README.md
Labels: type/docs, priority/low, sev/low, size/xs

#153 Updates post-v22.01
  .github/ISSUE_TEMPLATE/bug.yml
  CHANGELOG.md
  builds/common.pkrvars.hcl.example
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/7/variables.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8-stream/variables.pkr.hcl
  builds/linux/centos/8/linux-centos.pkr.hcl
  builds/linux/centos/8/variables.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/4/variables.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/7/variables.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/8/variables.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/8/variables.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2016/variables.pkr.hcl
  builds/windows/server/2016/windows-server.pkr.hcl
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/variables.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  set-envvars.sh
Labels: type/docs, type/refactor, priority/low, sev/low, size/m

#155 Updates post-v22.01
  builds/windows/desktop/11/windows.auto.pkrvars.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Labels: priority/low, sev/low, size/s, type/chore
