Repository vmware/packer-examples-for-vsphere, pull requests merged in 2022-04, with the labels that each got.

#185 feat: Prepare Ubuntu 22.04
  README.md
  ansible/roles/configure/tasks/ubuntu.yml
  build.sh
  build.yaml
  builds/linux/ubuntu/22-04-lts/data/meta-data
  builds/linux/ubuntu/22-04-lts/data/user-data.pkrtpl.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.auto.pkrvars.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
Labels: type/enhancement, status/in-progress, status/planned, status/needs-review, priority/medium, sev/low

#193 docs: Fix a mistake in README.md for Configuration, Step 2.3
  README.md
Labels: type/docs, status/needs-review, priority/low, sev/low, size/xs

#198 fix: gh-197
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8/linux-centos.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
Labels: type/bug, priority/medium, sev/low, size/s

#201 fix: Update checksum for CentOS 7 (`CentOS-7-x86_64-DVD-2009.iso`)
  builds/linux/centos/7/linux-centos.auto.pkrvars.hcl
Labels: type/bug, priority/low, status/confirmed, sev/low, status/acknowledged, size/xs
