Repository vmware/packer-examples-for-vsphere, pull requests merged in 2022-12, with the labels that each got.

#387 feat: Allow SSH authentication with RSA keys
  README.md
  ansible/ansible.cfg
Labels: type/feature, size/s

#403 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: type/docs

#404 fix(ansible): update configure task name
  ansible/roles/configure/tasks/main.yml
Labels: type/bug

#405 docs: update `README.md`
  README.md
Labels: type/docs

#407 docs: update `README.md`
  README.md
Labels: type/docs

#416 chore(deps): bump packer-plugin-vsphere from v1.1.0 to v1.1.1
  .github/ISSUE_TEMPLATE/bug.yml
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/chore, dependencies

#417 chore(deps): bump centos stream 8 to latest
  builds/linux/centos/8-stream/linux-centos-stream.auto.pkrvars.hcl
Labels: type/chore, dependencies

#418 chore(deps): bump centos stream 9 to latest
  builds/linux/centos/9-stream/linux-centos-stream.auto.pkrvars.hcl
Labels: type/chore, dependencies

#419 chore(deps): bump windows server 2022 to latest
  builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Labels: type/chore, dependencies

#420 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: type/docs, type/chore

#421 fix: remove country code for ubuntu
  builds/linux/ubuntu/20-04-lts/data/user-data.pkrtpl.hcl
  builds/linux/ubuntu/22-04-lts/data/user-data.pkrtpl.hcl
Labels: type/bug

#423 chore(deps): bump packer from v1.8.4 to v1.8.5
  .github/ISSUE_TEMPLATE/bug.yml
  CHANGELOG.md
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/chore, dependencies

#436 fix: update `output_directory` variable
  builds/windows/server/2019/windows-server.pkr.hcl
Labels: type/bug

#437 fix: revert winrm args
  builds/windows/desktop/10/windows.auto.pkrvars.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.auto.pkrvars.hcl
  builds/windows/server/2019/windows-server.auto.pkrvars.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.auto.pkrvars.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/bug
