Repository vmware/packer-examples-for-vsphere, pull requests merged in 2022-08, with the labels that each got.

#243 chore: Auto-generate `.github/dependabot.yml`
  .github/dependabot.yml
  .github/generate-dependabot.sh
Labels: priority/low, sev/low, type/chore

#244 chore: update `.gitignore`
  .gitignore
Labels: type/chore

#195 feat: Add Debian 11 machine image
  README.md
  build.sh
  build.yaml
  builds/linux/debian/11/data/ks.pkrtpl.hcl
  builds/linux/debian/11/linux-debian.auto.pkrvars.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/11/variables.pkr.hcl
Labels: status/planned, priority/medium, type/feature

#245 feat: add Debian 11 machine image Ansible playbooks
  ansible/roles/base/tasks/debian.yml
  ansible/roles/base/tasks/main.yml
  ansible/roles/clean/tasks/debian.yml
  ansible/roles/clean/tasks/main.yml
  ansible/roles/configure/tasks/debian.yml
  ansible/roles/configure/tasks/main.yml
  ansible/roles/users/tasks/main.yml
Labels: status/planned, priority/medium, type/feature

#246 chore(deps): bump Packer plugin for vSphere from v1.0.6 to v1.0.7
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: type/chore

#247 chore(deps): bump Terraform from v1.2.5 to v1.2.7
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore

#248 chore(deps): bump Packer plugin for vSphere from v1.0.7 to v1.0.8
  CHANGELOG.md
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
Labels: priority/medium, sev/low, size/s, type/chore

#251 chore(deps): bump .iso to August 2022 revisions for Windows guest operating systems
  builds/windows/desktop/10/windows.auto.pkrvars.hcl
  builds/windows/desktop/11/windows.auto.pkrvars.hcl
  builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Labels: priority/high, sev:minor, size/xs, type/chore

#236 feat: Add support for HCP Packer
  .gitignore
  README.md
  builds/common.pkrvars.hcl.example
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/variables.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/7/variables.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8-stream/variables.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/variables.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/11/variables.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/4/variables.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/7/variables.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/8/variables.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rhel/9/variables.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/8/variables.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/rocky/9/variables.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/sles/15/variables.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/18-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/variables.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  set-envvars.sh
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/main.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/terraform.tfvars.example
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/variables.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/main.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/terraform.tfvars.example
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/variables.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/main.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/terraform.tfvars.example
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/variables.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
Labels: priority/medium, sev/low, type/feature, size/m

#254 chore: Update versions in the `.github/ISSUE_TEMPLATES` for `v22.07`.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/pull_request_template.md
Labels: type/bug, priority/medium, type/chore

#255 chore: Update versions in the `.github/ISSUE_TEMPLATES` for `v22.08`.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/pull_request_template.md
Labels: priority/high, sev/low, size/xs, type/chore

#258 chore(deps): bump Terraform from v1.2.7 to v1.2.8
  CHANGELOG.md
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: priority/medium, sev/low, type/chore, dependencies
