Repository vmware/packer-examples-for-vsphere, pull requests merged in 2022-03, with the labels that each got.

#173 chore: :arrow_up: Update dependencies
  .github/ISSUE_TEMPLATE/bug.yml
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8/linux-centos.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2016/windows-server.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: priority/low, sev/low, size/m, type/chore

#172 refactor: :recycle: Remove Ansible package
  builds/linux/almalinux/8/data/ks.pkrtpl.hcl
  builds/linux/centos/7/data/ks.pkrtpl.hcl
  builds/linux/centos/8-stream/data/ks.pkrtpl.hcl
  builds/linux/centos/8/data/ks.pkrtpl.hcl
  builds/linux/photon/4/data/ks.pkrtpl.hcl
  builds/linux/rhel/7/data/ks.pkrtpl.hcl
  builds/linux/rhel/8/data/ks.pkrtpl.hcl
  builds/linux/rocky/8/data/ks.pkrtpl.hcl
  builds/linux/ubuntu/18-04-lts/data/ks.pkrtpl.hcl
  builds/linux/ubuntu/20-04-lts/data/user-data.pkrtpl.hcl
Labels: type/refactor, priority/low, sev/low, size/s

#174 chore: :arrow_up: Update versions in `issue_templates`
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
Labels: priority/low, sev/low, size/s, type/chore

#179 fix: :wrench: Correct `boot_command` for RHEL and derivatives
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8/linux-centos.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
Labels: type/bug, priority/medium, sev/low, size/s

#182 fix: :wrench: Update Python interpreter for Ansible on AlmaLinux
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
Labels: type/bug, priority/high, status/confirmed, sev:minor, size/xs

#184 chore: ♻️ Update Ubuntu 20.04 LTS .iso to v20.04.4
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.auto.pkrvars.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
Labels: priority/low, sev/low, size/xs, type/chore

#188 feat: Add a configurable build script
  .github/workflows/code-quality.yml
  README.md
  build.sh
  build.tmpl
  build.yaml
Labels: type/enhancement, status/in-progress, status/planned, status/needs-review, priority/medium, sev/low

#191 bug: Fix `iso_checksum_value` value
  builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Labels: type/bug, priority/low, sev/low, size/xs
