Repository vmware/packer-examples-for-vsphere, pull requests merged in 2023-01, with the labels that each got.

#440 fix: update EPEL repo version for RHEL 9
  builds/linux/rhel/9/data/ks.pkrtpl.hcl
Labels: type/bug

#439 fix: update `README.md`
  README.md
Labels: type/docs

#443 refactor: remove `args: warn` for ansible-core 2.14+
  ansible/roles/base/tasks/photon.yml
  ansible/roles/clean/tasks/debian.yml
  ansible/roles/clean/tasks/photon.yml
  ansible/roles/clean/tasks/redhat.yml
  ansible/roles/clean/tasks/sles.yml
  ansible/roles/clean/tasks/ubuntu.yml
  ansible/roles/configure/tasks/debian.yml
  ansible/roles/configure/tasks/photon.yml
  ansible/roles/configure/tasks/redhat.yml
  ansible/roles/configure/tasks/sles.yml
  ansible/roles/configure/tasks/ubuntu.yml
  ansible/roles/users/tasks/linux.yml
  ansible/roles/users/tasks/photon.yml
Labels: type/refactor, area/ansible

#432 chore(deps): bump debian from v11.5 to v11.6
  CHANGELOG.md
  README.md
  ansible/roles/configure/tasks/debian.yml
  builds/linux/debian/11/linux-debian.auto.pkrvars.hcl
Labels: type/chore, dependencies

#444 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: type/docs

#445 chore: update copyright
  LICENSE
  NOTICE
Labels: type/chore

#450 chore(deps): bump windows 10 to 22h2 to latest
  builds/windows/desktop/10/windows.auto.pkrvars.hcl
Labels: type/chore, dependencies

#451 chore(deps): bump windows 11 to 22h2 latest
  builds/windows/desktop/11/windows.auto.pkrvars.hcl
Labels: type/chore, dependencies

#452 chore(deps): bump windows server 2022 to latest
  builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Labels: type/chore, dependencies

#453 chore(deps): bump centos stream 8 to latest
  builds/linux/centos/8-stream/linux-centos-stream.auto.pkrvars.hcl
Labels: type/chore, dependencies

#454 chore(deps): bump centos stream 9 to latest
  builds/linux/centos/9-stream/linux-centos-stream.auto.pkrvars.hcl
Labels: type/chore, dependencies

#455 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: type/docs

#456 chore(deps): bump terraform from v1.3.6 to v1.3.7
  CHANGELOG.md
  README.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, dependencies

#457 fix: update cloud-init terraform examples
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/userdata.yml
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/userdata.yml
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/userdata.yml
  terraform/vsphere-virtual-machine/template-linux-cloud-init/userdata.yml
Labels: type/bug, size/xs, terraform
