Repository vmware/packer-examples-for-vsphere, pull requests merged in 2023-09, with the labels that each got.

#661 chore: update to `develop` branch
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/workflows/code-quality.yml
  CONTRIBUTING.md
  README.md
Labels: type/chore, cla-not-required

#675 feat: add templated `.gitlab-ci.yml` method
  .gitlab-ci.yml
  CHANGELOG.md
  README.md
  build-ci.tmpl
Labels: status/planned, status/awaitng-response, cla-not-required

#670 feat: add oracle linux
  CHANGELOG.md
  README.md
  ansible/roles/base/tasks/main.yml
  ansible/roles/clean/tasks/main.yml
  ansible/roles/configure/tasks/main.yml
  ansible/roles/users/tasks/main.yml
  build.sh
  build.yaml
  builds/linux/oracle/8/data/ks.pkrtpl.hcl
  builds/linux/oracle/8/linux-oel.auto.pkrvars.hcl
  builds/linux/oracle/8/linux-oel.pkr.hcl
  builds/linux/oracle/8/variables.pkr.hcl
  builds/linux/oracle/9/data/ks.pkrtpl.hcl
  builds/linux/oracle/9/linux-oel.auto.pkrvars.hcl
  builds/linux/oracle/9/linux-oel.pkr.hcl
  builds/linux/oracle/9/variables.pkr.hcl
Labels: type/enhancement, status/planned, status/awaitng-response

#688 feat: add support for windows 10/11 enterprise
  .gitlab-ci.yml
  CHANGELOG.md
  README.md
  build.sh
  build.yaml
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/10/windows.auto.pkrvars.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/desktop/11/windows.auto.pkrvars.hcl
  builds/windows/desktop/11/windows.pkr.hcl
Labels: status/planned, cla-not-required

#702 Fix for issue #701
  .gitlab-ci.yml
  build-ci.tmpl
Labels: cla-not-required

#700 chore: add devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  CHANGELOG.md
Labels: type/chore, cla-not-required

#705 feat: add logging to `set-envvars.sh`
  CHANGELOG.md
  set-envvars.sh
Labels: type/enhancement, cla-not-required

#471 feat: support non drs environments
  CHANGELOG.md
  README.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/variables.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/7/variables.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8-stream/variables.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/variables.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/11/variables.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/debian/12/variables.pkr.hcl
  builds/linux/oracle/8/linux-oel.pkr.hcl
  builds/linux/oracle/8/variables.pkr.hcl
  builds/linux/oracle/9/linux-oel.pkr.hcl
  builds/linux/oracle/9/variables.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/4/variables.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/photon/5/variables.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/7/variables.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/8/variables.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rhel/9/variables.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/8/variables.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/rocky/9/variables.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/sles/15/variables.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
  builds/vsphere.pkrvars.hcl.example
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/variables.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  set-envvars.sh
Labels: type/enhancement, status/planned

#706 feat: add debug
  CHANGELOG.md
  README.md
  build.sh
  build.tmpl
  build.yaml
Labels: type/enhancement, cla-not-required
