Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-07, with the labels that each got.

#944 refactor: updating linux pkr.hcl
  CHANGELOG.md
  ansible/roles/base/tasks/debian.yml
  ansible/roles/base/tasks/suse.yml
  builds/linux/centos/7/linux-centos.pkrvars.hcl.example
  builds/linux/centos/7/variables.pkr.hcl
  builds/linux/centos/9/linux-centos-stream.pkrvars.hcl.example
  builds/linux/centos/9/variables.pkr.hcl
  builds/linux/debian/11/linux-debian.pkrvars.hcl.example
  builds/linux/debian/11/variables.pkr.hcl
  builds/linux/debian/12/linux-debian.pkrvars.hcl.example
  builds/linux/debian/12/variables.pkr.hcl
  builds/linux/fedora/40/linux-fedora.pkrvars.hcl.example
  builds/linux/fedora/40/variables.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkrvars.hcl.example
  builds/linux/oracle/8/variables.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkrvars.hcl.example
  builds/linux/oracle/9/variables.pkr.hcl
  builds/linux/photon/4/linux-photon.pkrvars.hcl.example
  builds/linux/photon/4/variables.pkr.hcl
  builds/linux/photon/5/linux-photon.pkrvars.hcl.example
  builds/linux/photon/5/variables.pkr.hcl
  builds/linux/rhel/7/data/ks.pkrtpl.hcl
  builds/linux/rhel/7/data/network.pkrtpl.hcl
  builds/linux/rhel/7/data/storage.pkrtpl.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkrvars.hcl.example
  builds/linux/rhel/7/variables-network.pkr.hcl
  builds/linux/rhel/7/variables-storage.pkr.hcl
  builds/linux/rhel/7/variables.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkrvars.hcl.example
  builds/linux/rhel/8/variables.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkrvars.hcl.example
  builds/linux/rhel/9/variables.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkrvars.hcl.example
  builds/linux/rocky/8/variables.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkrvars.hcl.example
  builds/linux/rocky/9/variables.pkr.hcl
  builds/linux/sles/15/linux-sles.pkrvars.hcl.example
  builds/linux/sles/15/variables.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/24-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/24-04-lts/variables.pkr.hcl
  docs/index.md
  project.json
Labels: cla-not-required

#945 refactor: updating windows os pkr.hcl
  CHANGELOG.md
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/10/windows.pkrvars.hcl.example
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/desktop/11/windows.pkrvars.hcl.example
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2019/windows-server.pkrvars.hcl.example
  builds/windows/server/2022/variables.pkr.hcl
  builds/windows/server/2022/windows-server.pkrvars.hcl.example
  builds/windows/server/2025/variables.pkr.hcl
  builds/windows/server/2025/windows-server.pkrvars.hcl.example
Labels: cla-not-required

#948 docs: updated readme
  CHANGELOG.md
  README.md
  builds/vsphere.pkrvars.hcl.example
  docs/getting-started/configure.md
Labels: type/docs, cla-not-required

#951 fix: skipped tasks due to wrong when condition
  ansible/roles/base/tasks/redhat.yml
Labels: type/bug
