Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-02, with the labels that each got.

#835 fix: debian boot delay
  builds/linux/debian/11/linux-debian.pkrvars.hcl.example
  builds/linux/debian/11/variables.pkr.hcl
  builds/linux/debian/12/linux-debian.pkrvars.hcl.example
  builds/linux/debian/12/variables.pkr.hcl
Labels: type/bug, cla-not-required

#801 feat: add support for ansible integration for windows images
  CHANGELOG.md
  ansible/linux-playbook.yml
  ansible/linux-requirements.yml
  ansible/roles/base/tasks/main.yml
  ansible/roles/base/tasks/windows.yml
  ansible/roles/configure/tasks/main.yml
  ansible/roles/configure/tasks/windows.yml
  ansible/windows-playbook.yml
  ansible/windows-requirements.yml
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/almalinux/9/variables.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/7/variables.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/8-stream/variables.pkr.hcl
  builds/linux/centos/9-stream/variables.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/11/variables.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/debian/12/variables.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/8/variables.pkr.hcl
  builds/linux/oracle/9/variables.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/4/variables.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/photon/5/variables.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/7/variables.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/8/variables.pkr.hcl
  builds/linux/rhel/9/variables.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/8/variables.pkr.hcl
  builds/linux/rocky/9/variables.pkr.hcl
  builds/linux/sles/15/variables.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/23-10/variables.pkr.hcl
  builds/windows/desktop/10/data/autounattend.pkrtpl.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/10/windows.pkrvars.hcl.example
  builds/windows/desktop/11/data/autounattend.pkrtpl.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkrvars.hcl.example
  builds/windows/server/2019/data/autounattend.pkrtpl.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2019/windows-server.pkrvars.hcl.example
  builds/windows/server/2022/data/autounattend.pkrtpl.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkrvars.hcl.example
  builds/windows/server/2025/data/autounattend.pkrtpl.hcl
  builds/windows/server/2025/windows-server.pkr.hcl
  builds/windows/server/2025/windows-server.pkrvars.hcl.example
  config.sh
  scripts/windows/windows-prepare.ps1
  scripts/windows/windows-vmtools.ps1
Labels: type/enhancement, area/ansible

#838 fix: typo in playbook_file
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
Labels: cla-not-required

#839 fix: re-add `ansible_username` and `ansible_key` variables for windows builds
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2022/variables.pkr.hcl
  builds/windows/server/2025/variables.pkr.hcl
Labels: cla-not-required

#840 fix: add `ansible.pkrvars.hcl` and `proxy.pkrvars.hcl` to windows builds
  build.sh
  build.yaml
Labels: cla-not-required

#842 Fix Windows Server 2019 Desktop Experience builds
  ansible/roles/base/tasks/windows.yml
Labels: cla-not-required
