Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-03, with the labels that each got.

#844 feat: use windows os evaluation
  CHANGELOG.md
  README.md
  builds/windows/desktop/10/data/autounattend.pkrtpl.hcl
  builds/windows/desktop/10/variables.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/10/windows.pkrvars.hcl.example
  builds/windows/desktop/11/data/autounattend.pkrtpl.hcl
  builds/windows/desktop/11/variables.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkrvars.hcl.example
  builds/windows/server/2019/data/autounattend.pkrtpl.hcl
  builds/windows/server/2019/variables.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2019/windows-server.pkrvars.hcl.example
  builds/windows/server/2022/data/autounattend.pkrtpl.hcl
  builds/windows/server/2022/variables.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkrvars.hcl.example
  builds/windows/server/2025/data/autounattend.pkrtpl.hcl
  builds/windows/server/2025/variables.pkr.hcl
  builds/windows/server/2025/windows-server.pkr.hcl
  builds/windows/server/2025/windows-server.pkrvars.hcl.example
  docs/getting-started/build.md
  docs/getting-started/iso.md
  docs/getting-started/requirements.md
  docs/index.md
Labels: type/enhancement

#843 refactor: ubuntu cloud-init
  .gitlab-ci.yml
  CHANGELOG.md
  ansible/roles/clean/tasks/debian.yml
  ansible/roles/configure/tasks/debian.yml
  ansible/roles/users/tasks/linux.yml
  build-ci.tmpl
  build.sh
  build.tmpl
  build.yaml
  builds/build.pkrvars.hcl.example
  builds/linux-storage.pkrvars.hcl.example
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/23-10/variables.pkr.hcl
  builds/proxy.pkrvars.hcl.example
  builds/rhsm.pkrvars.hcl.example
  builds/scc.pkrvars.hcl.example
  builds/vsphere.pkrvars.hcl.example
  docs/getting-started/configuration.md
  docs/getting-started/download.md
  docs/index.md
Labels: type/refactor, cla-not-required

#860 chore: upgrade `almalinux-release`
  CHANGELOG.md
  ansible/linux-requirements.yml
  ansible/roles/base/tasks/linux.yml
  ansible/windows-requirements.yml
Labels: area/ansible, cla-not-required

#862 chore: reflow markdown
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  MAINTAINERS.md
  Makefile
  docs/getting-started/build.md
  docs/getting-started/configuration.md
  docs/getting-started/download.md
  docs/getting-started/gitlab-ci-cd.md
  docs/getting-started/iso.md
  docs/getting-started/privileges.md
  docs/getting-started/requirements.md
Labels: type/chore, cla-not-required

#863 chore(deps): bump ubuntu from v22.04.3 to v22.04.4
  CHANGELOG.md
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkrvars.hcl.example
Labels: type/chore, cla-not-required, dependencies

#864 chore(deps): bump debian from v11.8 to v11.9.
  CHANGELOG.md
  builds/linux/debian/11/linux-debian.pkrvars.hcl.example
Labels: type/chore, cla-not-required, dependencies

#865 chore(deps): bump debian from v12.4 to v12.5
  CHANGELOG.md
  builds/linux/debian/12/linux-debian.pkrvars.hcl.example
Labels: type/chore, cla-not-required, dependencies

#866 chore(deps): bumperraform-provider-vsphere from v2.6.1 to v2.7.0
  CHANGELOG.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, cla-not-required, dependencies

#867 chore(deps): bump terraform-provider-hcp from v0.81.0 to v0.84.1
  CHANGELOG.md
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
Labels: type/chore, cla-not-required, dependencies

#868 chore(deps): bump packer-plugin-git from v0.6.1 to v0.6.2
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  builds/windows/server/2025/windows-server.pkr.hcl
  docs/getting-started/requirements.md
Labels: type/chore, cla-not-required, dependencies

#869 chore: .vscode
  .vscode/extensions.json
  .vscode/settings.json
Labels: type/chore, cla-not-required
