Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-04, with the labels that each got.

#871 chore(deps): bump packer-plugin-vsphere from v1.2.1 to v1.2.4
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  builds/windows/server/2025/windows-server.pkr.hcl
Labels: type/chore, cla-not-required, dependencies

#873 chore(deps): bump packer-plugin-vsphere from v1.2.1 to v1.2.7
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  builds/windows/server/2025/windows-server.pkr.hcl
  docs/getting-started/requirements.md
Labels: type/chore, cla-not-required, dependencies

#874 feat: gos iso download automation
  CHANGELOG.md
  download.sh
  project.json
Labels: cla-not-required

#879 fix: windows pwsh provisioner
  CHANGELOG.md
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
Labels: type/bug, cla-not-required

#876 feat: add check for iso
  download.sh
Labels: type/enhancement, cla-not-required

#877 feat: add url check before download
  CHANGELOG.md
  download.sh
Labels: type/enhancement, cla-not-required

#881 chore: update gos iso download automation
  download.sh
  project.json
Labels: type/chore, cla-not-required

#882 chore: update `project.json`
  project.json
Labels: type/chore, cla-not-required

#883 feat: option to enable cloud-init on debian 12.5
  CHANGELOG.md
  ansible/roles/configure/tasks/debian.yml
  builds/linux/debian/12/data/ks.pkrtpl.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkrvars.hcl.example
  builds/linux/debian/12/variables.pkr.hcl
  docs/index.md
Labels: type/enhancement, cla-not-required

#887 chore: add rhel7 to `project.json`
  project.json
Labels: type/chore, cla-not-required

#895 feat: option to enable cloud-init on rocky linux 9 and 8
  CHANGELOG.md
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkrvars.hcl.example
  builds/linux/rocky/8/variables.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkrvars.hcl.example
  builds/linux/rocky/9/variables.pkr.hcl
  docs/index.md
Labels: type/enhancement, cla-not-required

#891 feat: add ubuntu 24.04 lts
  .gitlab-ci.yml
  CHANGELOG.md
  README.md
  build.sh
  build.yaml
  builds/linux/ubuntu/24-04-lts/data/meta-data
  builds/linux/ubuntu/24-04-lts/data/network.pkrtpl.hcl
  builds/linux/ubuntu/24-04-lts/data/storage.pkrtpl.hcl
  builds/linux/ubuntu/24-04-lts/data/user-data.pkrtpl.hcl
  builds/linux/ubuntu/24-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/24-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/24-04-lts/variables-network.pkr.hcl
  builds/linux/ubuntu/24-04-lts/variables-storage.pkr.hcl
  builds/linux/ubuntu/24-04-lts/variables.pkr.hcl
  docs/getting-started/iso.md
  docs/index.md
  project.json
Labels: type/enhancement, cla-not-required

#898 feat: added cloud-init to almalinux 8 and 9
  CHANGELOG.md
  ansible/roles/base/tasks/linux.yml
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/8/linux-almalinux.pkrvars.hcl.example
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkrvars.hcl.example
  builds/linux/almalinux/9/variables.pkr.hcl
  docs/index.md
Labels: type/enhancement, cla-not-required

#899 feat: added cloud-init to oracle linux 8 and 9
  CHANGELOG.md
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkrvars.hcl.example
  builds/linux/oracle/8/variables.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkrvars.hcl.example
  builds/linux/oracle/9/variables.pkr.hcl
  docs/index.md
Labels: type/enhancement, cla-not-required

#900 feat: added cloud-init to photon 4 and 5
  CHANGELOG.md
  ansible/roles/base/tasks/linux.yml
  docs/index.md
  project.json
Labels: type/enhancement, cla-not-required

#901 chore: updated cloud-init on debian 12
  ansible/roles/base/tasks/linux.yml
  builds/linux/debian/12/data/ks.pkrtpl.hcl
Labels: type/chore, cla-not-required

#904 fix: ansible base role
  ansible/roles/base/tasks/linux.yml
Labels: type/bug

#907 fix: update windows 2025 defaults
  CHANGELOG.md
  builds/windows/server/2025/windows-server.pkrvars.hcl.example
Labels: type/bug

#908 fix: windows desktop evaluation
  CHANGELOG.md
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/10/windows.pkrvars.hcl.example
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkrvars.hcl.example
  docs/getting-started/faq.md
Labels: type/bug, cla-not-required
