Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-05, with the labels that each got.

#919 feat: added cloud-init to sles
  CHANGELOG.md
  ansible/roles/base/tasks/linux.yml
  ansible/roles/configure/tasks/suse.yml
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/sles/15/linux-sles.pkrvars.hcl.example
  builds/linux/sles/15/variables.pkr.hcl
  docs/index.md
Labels: type/enhancement, cla-not-required

#910 feat: updated build.sh to use a json for files
  .github/workflows/requirements.txt
  .gitlab-ci.yml
  .trunk/tools
  CHANGELOG.md
  Makefile
  build-ci.tmpl
  build-ci.yaml
  build.sh
  build.tmpl
  builds/linux/centos/8/data/ks.pkrtpl.hcl
  builds/linux/centos/8/data/network.pkrtpl.hcl
  builds/linux/centos/8/data/storage.pkrtpl.hcl
  builds/linux/centos/8/linux-centos-stream.pkr.hcl
  builds/linux/centos/8/linux-centos-stream.pkrvars.hcl.example
  builds/linux/centos/8/variables-network.pkr.hcl
  builds/linux/centos/8/variables-storage.pkr.hcl
  builds/linux/centos/8/variables.pkr.hcl
  builds/linux/centos/9/data/ks.pkrtpl.hcl
  builds/linux/centos/9/data/network.pkrtpl.hcl
  builds/linux/centos/9/data/storage.pkrtpl.hcl
  builds/linux/centos/9/linux-centos-stream.pkr.hcl
  builds/linux/centos/9/linux-centos-stream.pkrvars.hcl.example
  builds/linux/centos/9/variables-network.pkr.hcl
  builds/linux/centos/9/variables-storage.pkr.hcl
  builds/linux/centos/9/variables.pkr.hcl
  docs/assets/images/build.gif
  docs/assets/images/download.gif
  docs/assets/stylesheets/spanable.css
  docs/getting-started/build.md
  docs/getting-started/configuration.md
  docs/getting-started/configure.md
  docs/getting-started/downloads.md
  docs/getting-started/get-project.md
  docs/getting-started/iso.md
  docs/getting-started/privileges.md
  docs/getting-started/requirements.md
  docs/index.md
  mkdocs.yml
  project.json
Labels: type/enhancement, cla-not-required

#923 feat: add title to menu's for build and download
  build.sh
  download.sh
Labels: cla-not-required

#924 Feat/add dependencies check
  build.sh
  docs/getting-started/build.md
  project.json
Labels: cla-not-required

#925 chore(deps): bump rhel from v9.3 to v9.4
  CHANGELOG.md
  builds/linux/rhel/9/linux-rhel.pkrvars.hcl.example
  project.json
Labels: type/chore, cla-not-required, dependencies

#926 refactor: update `download.sh`
  download.sh
Labels: type/refactor, cla-not-required

#930 feat: use evaluation for Windows Server 2025
  CHANGELOG.md
  builds/windows/server/2025/windows-server.pkrvars.hcl.example
  download.sh
  project.json
Labels: cla-not-required

#928 refactor: ansible playbooks for linux
  ansible/linux-requirements.yml
  ansible/roles/base/defaults/main.yml
  ansible/roles/base/tasks/debian.yml
  ansible/roles/base/tasks/linux.yml
  ansible/roles/base/tasks/main.yml
  ansible/roles/base/tasks/photon.yml
  ansible/roles/base/tasks/redhat.yml
  ansible/roles/base/tasks/suse.yml
  ansible/roles/base/tasks/windows.yml
  ansible/roles/base/vars/main.yml
  ansible/roles/clean/tasks/debian.yml
  ansible/roles/clean/tasks/photon.yml
  ansible/roles/clean/tasks/suse.yml
  ansible/roles/configure/defaults/main.yml
  ansible/roles/configure/tasks/debian.yml
  ansible/roles/configure/tasks/photon.yml
  ansible/roles/configure/tasks/redhat.yml
  ansible/roles/configure/tasks/suse.yml
  ansible/roles/configure/tasks/windows.yml
  ansible/roles/users/tasks/linux.yml
  ansible/windows-requirements.yml
  build.sh
  builds/linux/almalinux/8/linux-almalinux.pkrvars.hcl.example
  builds/linux/almalinux/9/linux-almalinux.pkrvars.hcl.example
  builds/linux/centos/9/linux-centos-stream.pkrvars.hcl.example
  builds/linux/debian/12/linux-debian.pkrvars.hcl.example
  builds/linux/fedora/40/linux-fedora.pkrvars.hcl.example
  builds/linux/oracle/8/linux-oracle.pkrvars.hcl.example
  builds/linux/oracle/9/linux-oracle.pkrvars.hcl.example
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/4/linux-photon.pkrvars.hcl.example
  builds/linux/photon/4/variables.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkrvars.hcl.example
  builds/linux/photon/5/variables.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkrvars.hcl.example
  builds/linux/rhel/9/linux-rhel.pkrvars.hcl.example
  builds/linux/rocky/8/linux-rocky.pkrvars.hcl.example
  builds/linux/rocky/9/linux-rocky.pkrvars.hcl.example
  builds/linux/sles/15/linux-sles.pkrvars.hcl.example
  builds/vsphere.pkrvars.hcl.example
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/10/windows.pkrvars.hcl.example
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkrvars.hcl.example
  terraform/vsphere-virtual-machine/template-linux-cloud-init/metadata.yml
Labels: type/refactor, area/ansible, cla-not-required
