Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-12, with the labels that each got.

#984 chore(deps): bump linux versions
  .gitignore
  CHANGELOG.md
  README.md
  build-ci.yaml
  builds/linux/almalinux/8/linux-almalinux.pkrvars.hcl.example
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkrvars.hcl.example
  builds/linux/centos/9/linux-centos-stream.pkrvars.hcl.example
  builds/linux/debian/11/linux-debian.pkrvars.hcl.example
  builds/linux/debian/12/linux-debian.pkrvars.hcl.example
  builds/linux/fedora/41/data/ks.pkrtpl.hcl
  builds/linux/fedora/41/data/network.pkrtpl.hcl
  builds/linux/fedora/41/data/storage.pkrtpl.hcl
  builds/linux/fedora/41/linux-fedora.pkr.hcl
  builds/linux/fedora/41/linux-fedora.pkrvars.hcl.example
  builds/linux/fedora/41/variables-network.pkr.hcl
  builds/linux/fedora/41/variables-storage.pkr.hcl
  builds/linux/fedora/41/variables.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkrvars.hcl.example
  builds/linux/oracle/9/linux-oracle.pkrvars.hcl.example
  builds/linux/photon/4/linux-photon.pkrvars.hcl.example
  builds/linux/photon/5/linux-photon.pkrvars.hcl.example
  builds/linux/rhel/8/linux-rhel.pkrvars.hcl.example
  builds/linux/rhel/9/linux-rhel.pkrvars.hcl.example
  builds/linux/rocky/8/linux-rocky.pkrvars.hcl.example
  builds/linux/rocky/9/linux-rocky.pkrvars.hcl.example
  builds/linux/sles/15/linux-sles.pkrvars.hcl.example
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/linux/ubuntu/24-04-lts/linux-ubuntu.pkrvars.hcl.example
  builds/windows/desktop/10/windows.pkrvars.hcl.example
  builds/windows/desktop/11/windows.pkrvars.hcl.example
  builds/windows/server/2019/windows-server.pkrvars.hcl.example
  builds/windows/server/2022/windows-server.pkrvars.hcl.example
  builds/windows/server/2025/windows-server.pkrvars.hcl.example
  docs/getting-started/downloads.md
  docs/index.md
  project.json
Labels: type/chore

#985 chore(deps): bump debian 11 to 11.11 release
  CHANGELOG.md
  builds/linux/debian/11/linux-debian.pkrvars.hcl.example
  project.json
Labels: type/chore, dependencies

#986 chore(deps): update dependencies
  .gitlab-ci.yml
  CHANGELOG.md
  build-ci.yaml
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/9/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/fedora/41/linux-fedora.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/24-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  builds/windows/server/2025/windows-server.pkr.hcl
  docs/getting-started/requirements.md
  project.json
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, dependencies

#987 feat: add confirmation before overwriting configuration files
  CHANGELOG.md
  config.sh
Labels: type/enhancement

#988 docs: update contributing guidelines
  CONTRIBUTING.md
Labels: type/docs

#989 feat: add CentOS Stream 10
  .gitlab-ci.yml
  CHANGELOG.md
  README.md
  build-ci.yaml
  builds/linux/centos/10/data/ks.pkrtpl.hcl
  builds/linux/centos/10/data/network.pkrtpl.hcl
  builds/linux/centos/10/data/storage.pkrtpl.hcl
  builds/linux/centos/10/linux-centos-stream.pkr.hcl
  builds/linux/centos/10/linux-centos-stream.pkrvars.hcl.example
  builds/linux/centos/10/variables-network.pkr.hcl
  builds/linux/centos/10/variables-storage.pkr.hcl
  builds/linux/centos/10/variables.pkr.hcl
  docs/getting-started/downloads.md
  docs/index.md
  project.json
Labels: type/enhancement

#991 fix: sles 15 SP5 python
  CHANGELOG.md
  ansible/linux-playbook.yml
  ansible/roles/base/tasks/suse.yml
  builds/linux/sles/15/data/autoinst.pkrtpl.hcl
Labels: type/bug
