Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-01, with the labels that each got.

#805 feat: growing ubuntu lvm partition
  CHANGELOG.md
  builds/linux-storage.pkrvars.hcl.example
  builds/linux/ubuntu/20-04-lts/data/storage.pkrtpl.hcl
  builds/linux/ubuntu/22-04-lts/data/storage.pkrtpl.hcl
  builds/linux/ubuntu/23-10/data/storage.pkrtpl.hcl
  docs/community/index.md
  docs/getting-started/configuration.md
  mkdocs.yml
Labels: type/enhancement

#813 fix: creating/updating .gitlab-ci.yml produces working .gitlab-ci.yml
  .gitlab-ci.yml
  build-ci.tmpl
Labels: cla-not-required

#816 chore: Update Windows 10/11, Windows Server 2022, and Debian 12 ISOs
  CHANGELOG.md
  builds/linux/debian/12/linux-debian.pkrvars.hcl.example
  builds/windows/desktop/10/windows.pkrvars.hcl.example
  builds/windows/desktop/11/windows.pkrvars.hcl.example
  builds/windows/server/2022/windows-server.pkrvars.hcl.example
Labels: cla-not-required

#817 chore: update AlmaLinux 8/9 ISOs
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkrvars.hcl.example
  builds/linux/almalinux/9/linux-almalinux.pkrvars.hcl.example
Labels: cla-not-required

#818 chore(deps): bump rhel from v8.8 to v8.9
  CHANGELOG.md
  builds/linux/rhel/8/linux-rhel.pkrvars.hcl.example
Labels: type/chore, cla-not-required, dependencies

#819 chore(deps): bump rhel from v9.2 to v9.3
  CHANGELOG.md
  builds/linux/rhel/9/linux-rhel.pkrvars.hcl.example
Labels: type/chore, cla-not-required, dependencies

#820 chore(deps): bump oel from v8.8 to v8.9
  CHANGELOG.md
  builds/linux/oracle/8/linux-oracle.pkrvars.hcl.example
Labels: type/chore, cla-not-required, dependencies

#821 chore(deps): bump oel from v9.2 to v9.3
  CHANGELOG.md
  builds/linux/oracle/9/linux-oracle.pkrvars.hcl.example
Labels: type/chore, cla-not-required, dependencies

#823 hore(deps): bump rocky from v9.2 to v9.3
  CHANGELOG.md
  builds/linux/rocky/9/linux-rocky.pkrvars.hcl.example
Labels: type/chore, cla-not-required, dependencies

#824 chore(deps): bump packer-plugin-vsphere from v1.2.1 to v1.2.4
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  docs/getting-started/requirements.md
Labels: type/chore, cla-not-required, dependencies

#825 chore(deps): bump gomplate from v3.11.5 to v3.11.7
  CHANGELOG.md
  docs/getting-started/requirements.md
Labels: type/chore, cla-not-required, dependencies

#826 chore(deps): bump packer-plugin-windows-update from v0.14.3 to v0.15.0
  CHANGELOG.md
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  docs/getting-started/requirements.md
Labels: type/chore, cla-not-required, dependencies

#827 chore(deps): bump packer-plugin-git from v0.4.3 to v0.6.1
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  docs/getting-started/requirements.md
Labels: type/chore, cla-not-required, dependencies

#828 chore(deps): bump packer from v1.9.4 to v1.10.0
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
  builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/7/linux-rhel.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  docs/getting-started/requirements.md
Labels: type/chore, cla-not-required, dependencies

#829 chore(deps): bump terraform from v1.6.0 to v1.7.1
  CHANGELOG.md
  docs/getting-started/requirements.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, cla-not-required, dependencies

#830 chore(deps): bumperraform-provider-vsphere from v2.5.1 to v2.6.1
  CHANGELOG.md
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, cla-not-required, dependencies

#831 chore(deps): bumperraform-provider-hcp from v0.74.1 to v0.81.0
  CHANGELOG.md
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
Labels: type/chore, cla-not-required, dependencies

#832 fix: debian guest os identifier override
  ansible/roles/configure/tasks/debian.yml
Labels: type/bug, cla-not-required

#834 feat: add support for Windows Server 2025 Insiders Preview
  .gitlab-ci.yml
  CHANGELOG.md
  README.md
  build.sh
  build.yaml
  builds/windows/server/2025/data/autounattend.pkrtpl.hcl
  builds/windows/server/2025/variables.pkr.hcl
  builds/windows/server/2025/windows-server.pkr.hcl
  builds/windows/server/2025/windows-server.pkrvars.hcl.example
  docs/index.md
Labels: cla-not-required
