Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-09, with the labels that each got.

#960 chore: updated packer versions and debian
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkr.hcl
  builds/linux/centos/7/data/ks.pkrtpl.hcl
  builds/linux/centos/7/data/network.pkrtpl.hcl
  builds/linux/centos/7/data/storage.pkrtpl.hcl
  builds/linux/centos/7/linux-centos.pkr.hcl
  builds/linux/centos/7/linux-centos.pkrvars.hcl.example
  builds/linux/centos/7/variables-network.pkr.hcl
  builds/linux/centos/7/variables-storage.pkr.hcl
  builds/linux/centos/7/variables.pkr.hcl
  builds/linux/centos/9/linux-centos-stream.pkr.hcl
  builds/linux/debian/11/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkr.hcl
  builds/linux/debian/12/linux-debian.pkrvars.hcl.example
  builds/linux/fedora/40/linux-fedora.pkr.hcl
  builds/linux/oracle/8/linux-oracle.pkr.hcl
  builds/linux/oracle/9/linux-oracle.pkr.hcl
  builds/linux/photon/4/linux-photon.pkr.hcl
  builds/linux/photon/5/linux-photon.pkr.hcl
  builds/linux/rhel/8/linux-rhel.pkr.hcl
  builds/linux/rhel/9/linux-rhel.pkr.hcl
  builds/linux/rocky/8/linux-rocky.pkr.hcl
  builds/linux/rocky/9/linux-rocky.pkr.hcl
  builds/linux/sles/15/linux-sles.pkr.hcl
  builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
  builds/linux/ubuntu/24-04-lts/linux-ubuntu.pkr.hcl
  builds/windows/desktop/10/windows.pkr.hcl
  builds/windows/desktop/11/windows.pkr.hcl
  builds/windows/server/2019/windows-server.pkr.hcl
  builds/windows/server/2022/windows-server.pkr.hcl
  builds/windows/server/2025/windows-server.pkr.hcl
  docs/getting-started/requirements.md
  project.json
  terraform/vsphere-role/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
  terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Labels: type/chore, cla-not-required, dependencies

#965 chore: updated ubuntu 22.04.1
  CHANGELOG.md
  builds/linux/almalinux/8/linux-almalinux.pkrvars.hcl.example
  builds/linux/oracle/8/linux-oracle.pkrvars.hcl.example
  project.json
Labels: cla-not-required

#967 refactor: update devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: type/refactor, cla-not-required
