Repository vmware/packer-examples-for-vsphere, pull requests merged in 2024-06, with the labels that each got.

#934 refactor: ansible roles
  .vscode/settings.json
  .yamllint.yml
  ansible/linux-playbook.yml
  ansible/roles/base/defaults/main.yml
  ansible/roles/base/tasks/debian.yml
  ansible/roles/base/tasks/main.yml
  ansible/roles/base/tasks/photon.yml
  ansible/roles/base/tasks/redhat.yml
  ansible/roles/base/tasks/suse.yml
  ansible/roles/base/tasks/windows.yml
  ansible/roles/base/vars/main.yml
  ansible/roles/clean/tasks/debian.yml
  ansible/roles/clean/tasks/main.yml
  ansible/roles/clean/tasks/photon.yml
  ansible/roles/clean/tasks/redhat.yml
  ansible/roles/clean/tasks/suse.yml
  ansible/roles/clean/vars/main.yml
  ansible/roles/configure/defaults/main.yml
  ansible/roles/configure/tasks/debian.yml
  ansible/roles/configure/tasks/main.yml
  ansible/roles/configure/tasks/photon.yml
  ansible/roles/configure/tasks/redhat.yml
  ansible/roles/configure/tasks/suse.yml
  ansible/roles/configure/tasks/windows.yml
  ansible/roles/configure/vars/main.yml
  ansible/roles/users/tasks/linux.yml
  ansible/roles/users/tasks/main.yml
  ansible/roles/users/vars/main.yml
  ansible/windows-playbook.yml
  project.json
Labels: type/refactor, area/ansible, cla-not-required

#935 fix: use `volume_group.name` as the volgroup name
  builds/linux/almalinux/8/data/storage.pkrtpl.hcl
  builds/linux/almalinux/9/data/storage.pkrtpl.hcl
  builds/linux/centos/7/data/storage.pkrtpl.hcl
  builds/linux/centos/9/data/storage.pkrtpl.hcl
  builds/linux/fedora/40/data/storage.pkrtpl.hcl
  builds/linux/oracle/8/data/storage.pkrtpl.hcl
  builds/linux/oracle/9/data/storage.pkrtpl.hcl
  builds/linux/rhel/7/data/storage.pkrtpl.hcl
  builds/linux/rhel/8/data/storage.pkrtpl.hcl
  builds/linux/rhel/9/data/storage.pkrtpl.hcl
  builds/linux/rocky/8/data/storage.pkrtpl.hcl
  builds/linux/rocky/9/data/storage.pkrtpl.hcl
  tests/storage/templates/kickstart.pkrtpl
Labels: type/bug, size/xs, status/awaitng-response

#941 fix: issues with Base->redhat.yml
  ansible/roles/base/tasks/redhat.yml
Labels: type/bug, cla-not-required

#942 refactor: update variables for alma linux
  builds/linux/almalinux/8/linux-almalinux.pkrvars.hcl.example
  builds/linux/almalinux/8/variables.pkr.hcl
  builds/linux/almalinux/9/linux-almalinux.pkrvars.hcl.example
  builds/linux/almalinux/9/variables.pkr.hcl
Labels: type/refactor, cla-not-required
